name: Preview on Vercel + Lighthouse
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.vercel.outputs.PREVIEW_URL || steps.vercel.outputs.preview-url || steps.vercel.outputs.DEPLOYMENT_URL || steps.vercel.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - name: Install Vercel CLI (for action internal usage)
        run: npm install -g vercel@latest
      - name: Deploy to Vercel (Preview)
        id: vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # そのままでOK
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false

      - name: Echo preview url
        run: |
          echo "Preview: ${{ steps.vercel.outputs.PREVIEW_URL }}"

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Start local preview server
        run: |
          nohup npm run preview -- --port 4173 --strictPort >/dev/null 2>&1 &
          for i in {1..30}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4173)
            if [ "$code" = "200" ]; then
              echo "Local preview is ready."
              break
            fi
            echo "HTTP $code... retrying"
            sleep 2
          done
      - name: Audit URLs using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: http://localhost:4173
          budgetPath: ./.lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 1