name: Preview on Vercel + Lighthouse
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.vercel.outputs.PREVIEW_URL || steps.vercel.outputs.preview-url || steps.vercel.outputs.DEPLOYMENT_URL || steps.vercel.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - name: Install Vercel CLI (for action internal usage)
        run: npm install -g vercel@latest
      - name: Deploy to Vercel (Preview)
        id: vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # そのままでOK
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false

      - name: Echo preview url
        run: |
          echo "Preview: ${{ steps.vercel.outputs.PREVIEW_URL }}"

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ needs.deploy.outputs.preview_url }}
          budgetPath: ./.lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true